### PR TITLE
Fix: avatar loading when imagemagick support is not available

### LINKED ISSUE #99: wrong-type-argument consp nil
`matrix-client-connect` fails for me. Looks like it is some issue with the avatar.
```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  image--set-property(nil :max-width 35)
  matrix--room-display-name(#<matrix-room matrix-room-156b9a201760>)
```

### PR DESCRIPTION
**Pull request by seblemaguer**
Should fix #99

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks, this is probably a good change to make.  But please note that, if a user uses `setq` to set the variable, this won't prevent the problem.  So it's probably necessary to adjust the image-related code to handle nil values returned from the relevant functions (as mentioned in #99).

**Comment by seblemaguer** [comment]
Yes true. I will refactor that because that impacts also the following definition:

https://github.com/alphapapa/matrix-client.el/blob/59c792423fd0503f1375f356bec56130e65d3b51/matrix-client-images.el#L10-L19

I update the PR when I have a cleaner solution :)

**Comment by alphapapa** [comment]
That's not quite the solution I had in mind.  There's already a test for `(fboundp 'imagemagick-types)` here: https://github.com/alphapapa/matrix-client.el/blob/master/matrix-client-images.el#L73  That function, `matrix-client-rescale-image`, returns nil if that test fails.  It's that nil return value that needs to be handled in the code that calls that function.

Alternatively, the test could be moved to the earliest possible place in the code, to avoid calling the subsequent functions if images aren't supported.  But it might be better to handle the nil return values appropriately, because that might help avoid future bugs.

Also note that newer versions of Emacs don't necessarily require Imagemagick to handle images, so we might want to account for that when making changes now.

**Comment by seblemaguer** [comment]
Hello,

sorry got lost in work and then vacations. I re-attack this this week. 

I do agree with the management of `nil` in message returns. I still think it is more readable to have the constant `matrix-client-can-show-images` which is going to test if `imagemagick-types` is bounded or if the emacs version is new enough to not rely on imagemagick.

I update the PR and keep you in touch when I think it is ready.

**Comment by Thaodan** [comment]
>Also note that newer versions of Emacs don't necessarily require Imagemagick to handle images, so we might want to account for that when making changes now.

Look here for more on that:
https://github.com/jorgenschaefer/circe/pull/382

I'm using circe, that supports scaling all that out of the box without imagemagik that could work here too.

**Comment by alphapapa** [comment]
Closing issues and archiving repository. Please see https://github.com/alphapapa/ement.el for the new client.

**Pull request closed without merging**
