### PR TITLE
Update package.el headers

### PR DESCRIPTION
**Pull request by jgkamat**
For #47 

Right now, I've only changed the package headers, as the function renames are probably going to cause a lot of conflicts with the wip branch and need a bit more thought.

I like taking things small bits at a time :P 

I remvoed the json dependency since that seems to be in emacs > 25 anyway (which I added), and package-lint was complaining it couldn't be installed.

### CODE REVIEW

**Comment by alphapapa** [comment]
Hey, sorry, I forgot to comment on this.

Thanks for doing that.  You know, I'm not sure if we need to put the headers in every file.  We may only need to do that in one file, like the one that gets `require`ed.  That might simplify keeping things up-to-date too.  I mean, if you want to keep track of who originally made which file, and who has modified which file, that's cool, but I'd be happy with doing that in a single file too (or even letting the git history be used for that).  What do you think?

**Comment by jgkamat** [comment]
I'm definetly OK with only having the main file contain the headers, but I'm not sure if melpa is "ok" with that. Looking at something like [magit's files](https://github.com/magit/magit/blob/master/lisp/magit-imenu.el) for example, it looks like we can just have the copyright notice and author/maintainer, which I think is good enough. Because of that, I'll remove the headers from every file except `matrix-client`. Does that sound good to you? :)

**Comment by alphapapa** [comment]
> I'm definetly OK with only having the main file contain the headers, but I'm not sure if melpa is "ok" with that. 

Good point.  I *think* the only one that matters is the `-pkg.el` file (assuming we're going to have one), but I'd have to consult the docs again to be sure.

> Because of that, I'll remove the headers from every file except matrix-client. Does that sound good to you? :)

Sure!

**Comment by alphapapa** [comment]
Closing issues and archiving repository. Please see https://github.com/alphapapa/ement.el for the new client.

**Pull request closed without merging**
